# Generated by Django 5.2.8 on 2026-01-01 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('is_full_day', models.BooleanField(default=True, help_text='If false, only specific time slots are blocked')),
                ('blocked_from', models.TimeField(blank=True, help_text='Start time if partial day block', null=True)),
                ('blocked_until', models.TimeField(blank=True, help_text='End time if partial day block', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blocked Date',
                'verbose_name_plural': 'Blocked Dates',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ReservationsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot_duration', models.PositiveIntegerField(default=30, help_text='Duration of each time slot in minutes')),
                ('min_party_size', models.PositiveIntegerField(default=1, help_text='Minimum guests per reservation')),
                ('max_party_size', models.PositiveIntegerField(default=20, help_text='Maximum guests per reservation')),
                ('min_advance_hours', models.PositiveIntegerField(default=1, help_text='Minimum hours in advance to book')),
                ('max_advance_days', models.PositiveIntegerField(default=30, help_text='Maximum days in advance to book')),
                ('auto_confirm', models.BooleanField(default=False, help_text='Automatically confirm reservations')),
                ('require_phone', models.BooleanField(default=True, help_text='Require phone number for reservations')),
                ('require_email', models.BooleanField(default=False, help_text='Require email for reservations')),
                ('no_show_window_minutes', models.PositiveIntegerField(default=15, help_text='Minutes after reservation time to mark as no-show')),
                ('hold_table_minutes', models.PositiveIntegerField(default=120, help_text='Default reservation duration in minutes')),
                ('send_confirmation_email', models.BooleanField(default=False, help_text='Send email confirmation to guests')),
                ('send_reminder_email', models.BooleanField(default=False, help_text='Send reminder email before reservation')),
                ('reminder_hours_before', models.PositiveIntegerField(default=24, help_text='Hours before to send reminder')),
            ],
            options={
                'verbose_name': 'Reservations Configuration',
                'verbose_name_plural': 'Reservations Configuration',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=50)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_id', models.PositiveIntegerField(blank=True, help_text='Reference to customer in customers module', null=True)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('party_size', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField(default=120, help_text='Expected duration in minutes')),
                ('table_id', models.PositiveIntegerField(blank=True, help_text='Reference to table in tables module', null=True)),
                ('table_number', models.CharField(blank=True, default='', help_text='Table number for display', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Special requests or notes')),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Internal staff notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['date', 'status'], name='reservation_date_b616a1_idx'), models.Index(fields=['guest_phone'], name='reservation_guest_p_668570_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_reservations', models.PositiveIntegerField(default=10, help_text='Maximum reservations for this slot')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_phone', models.CharField(max_length=50)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('party_size', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, default='')),
                ('is_contacted', models.BooleanField(default=False)),
                ('is_converted', models.BooleanField(default=False, help_text='True if converted to a reservation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'ordering': ['date', 'preferred_time', 'created_at'],
            },
        ),
    ]
