# Generated by Django 6.0.2 on 2026-03-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockeddate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reservationsettings',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='blockeddate',
            constraint=models.UniqueConstraint(fields=('hub_id', 'date', 'blocked_from'), name='unique_blockeddate_per_hub'),
        ),
        migrations.AddConstraint(
            model_name='reservationsettings',
            constraint=models.UniqueConstraint(fields=('hub_id',), name='unique_reservation_settings_per_hub'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('hub_id', 'day_of_week', 'start_time', 'end_time'), name='unique_timeslot_per_hub'),
        ),
    ]
